<a href="https://colab.research.google.com/github/MoisesNb7/Control-hospitalario/blob/main/MoisesNavarreteDS25_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Datos del participante
Nombre: Moises Navarrete Bautista

Fecha: 24/06/2026

#Control hospitalario

Utiliza las secciones pertinentes para colocar la solución a cada uno de los requerimientos solicitados.

##Importa las librerías pertinentes para solucionar el reto.

In [16]:
import pandas as pd
import numpy as np

##Extrae la información del archivo.

In [17]:
# Abrir archivo
hospitalData = pd.read_excel('/content/hospitalData.xlsx')
# desplega
hospitalData

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of ICU Beds Occupied,Number of Adult ICU Beds Occupied,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications
0,12/08/23,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,1309.0,845.0,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS
1,12/08/23,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,1014.0,817.0,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN
2,12/08/23,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,468.0,446.0,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN
3,12/08/23,WY,1318.0,1142.0,25.0,559.0,534.0,6.0,114.0,109.0,...,40.0,40.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,AOCNP/JCI/CARN/CBN/CARN/JCI/ACS
4,19/08/23,AK,1354.0,1192.0,77.0,1054.0,939.0,43.0,184.0,126.0,...,139.0,86.0,8.0,11.0,1.0,NaN,NaN,NaN,NaN,CARN/ISO/AOCNP/CARN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12765,12/08/23,VA,16500.0,15161.0,911.0,11303.0,10467.0,594.0,2276.0,1856.0,...,1425.0,1188.0,121.0,155.0,6.0,NaN,NaN,NaN,NaN,CPAN/AOCNP/CPEN/DWC/CPEN/DWC/CPEN/CPEN/JCI/CCT...
12766,12/08/23,VI,168.0,152.0,16.0,89.0,82.0,3.0,17.0,14.0,...,7.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,CPEN/CPEN/AOCNP/CARN/CCTN/ISO/JCI/CPEN/CCTN/ACS
12767,12/08/23,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,81.0,65.0,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN
12768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9333.0,295183.0,NaN,NaN,3.727144,NaN,NaN

##Muestra la estructura y los tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas, asegúrandote de que las columnas con fechas sean del tipo datetime64.

In [18]:
# Visualiza los tipos de datos
hospitalData.info()
# Cambia el tipo de dato de object a datetime64
hospitalData['Week Ending Date'] = pd.to_datetime(hospitalData['Week Ending Date'])
# Visualiza los tipos de datos, se observa el cambio de tipo de dato
hospitalData.info()
print("El tipo de dato es:", hospitalData['Week Ending Date'].dtype)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12770 entries, 0 to 12769
Data columns (total 21 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Week Ending Date                                         12768 non-null  object
 1   Geographic aggregation                                   12768 non-null  object
 2   Number of Inpatient Beds                                 12521 non-null  float64
 3   Number of Adult Inpatient Beds                           12506 non-null  float64
 4   Number of Pediatric Inpatient beds                       12485 non-null  float64
 5   Number of Inpatient Beds Occupied                        12521 non-null  float64
 6   Number of Adult Inpatient Beds Occupied                  12510 non-null  float64
 7   Number of Pediatric Inpatient Beds Occupied              12494 non-null  float64
 8   Number of ICU Beds                                       12521 non-null  float64
 9   Number of Adult ICU Beds                                 12506 non-null  float64
 10  Number of Pediatric ICU Beds                             12485 non-null  float64
 11  Number of ICU Beds Occupied                              12521 non-null  float64
 12  Number of Adult ICU Beds Occupied                        12510 non-null  float64
 13  Number of Pediatric ICU Beds Occupied                    12494 non-null  float64
 14  Number of Adult Patients Hospitalized with COVID-19      12509 non-null  float64
 15  Number of Pediatric Patients Hospitalized with COVID-19  12500 non-null  float64
 16  Number of Adult Patients Hospitalized with Influenza     2034 non-null   float64
 17  Number of Pedatric Patients Hospitalized with Influenza  2028 non-null   float64
 18  Number of Adult Patients Hospitalized with RSV           2112 non-null   float64
 19  Number of Pediatric Patients Hospitalized with RSV       2109 non-null   float64
 20  Certifications                                           12768 non-null  object
dtypes: float64(18), object(3)
memory usage: 2.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12770 entries, 0 to 12769
Data columns (total 21 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Week Ending Date                                         12768 non-null  datetime64[ns]
 1   Geographic aggregation                                   12768 non-null  object
 2   Number of Inpatient Beds                                 12521 non-null  float64
 3   Number of Adult Inpatient Beds                           12506 non-null  float64
 4   Number of Pediatric Inpatient beds                       12485 non-null  float64
 5   Number of Inpatient Beds Occupied                        12521 non-null  float64
 6   Number of Adult Inpatient Beds Occupied                  12510 non-null  float64
 7   Number of Pediatric Inpatient Beds Occupied              12494 non-null  float64
 8   Number of ICU Beds                                       12521 non-null  float64
 9   Number of Adult ICU Beds                                 12506 non-null  float64
 10  Number of Pediatric ICU Beds                             12485 non-null  float64
 11  Number of ICU Beds Occupied                              12521 non-null  float64
 12  Number of Adult ICU Beds Occupied                        12510 non-null  float64
 13  Number of Pediatric ICU Beds Occupied                    12494 non-null  float64
 14  Number of Adult Patients Hospitalized with COVID-19      12509 non-null  float64
 15  Number of Pediatric Patients Hospitalized with COVID-19  12500 non-null  float64
 16  Number of Adult Patients Hospitalized with Influenza     2034 non-null   float64
 17  Number of Pedatric Patients Hospitalized with Influenza  2028 non-null   float64
 18  Number of Adult Patients Hospitalized with RSV           2112 non-null   float64
 19  Number of Pediatric Patients Hospitalized with RSV       2109 non-null   float64
 20  Certifications                                           12768 non-null  object
dtypes: datetime64[ns](1), float64(18), object(2)
memory usage: 2.0+ MB
El tipo de dato es: datetime64[ns]

/tmp/ipykernel_2414/1202299040.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  hospitalData['Week Ending Date'] = pd.to_datetime(hospitalData['Week Ending Date'])

##Elimina los registros con el código geográfico MP.

In [19]:
hospitalData.shape
# Conteo previo para verificar registros a eliminar
registros_mp_antes = (hospitalData['Geographic aggregation'] == 'MP').sum()
print(f"Registros con código 'MP' antes de eliminar: {registros_mp_antes}")

# Eliminación de los registros solicitados
hospitalData = hospitalData[hospitalData['Geographic aggregation'] != 'MP'].copy()

# conteo despues de eleminar en 0
registros_mp_despues = (hospitalData['Geographic aggregation'] == 'MP').sum()
print(f"Registros con código 'MP' después de eliminar: {registros_mp_despues}")
# Muestra el nuevo tamaño
print(f"Nuevas dimensiones del DataFrame: {hospitalData.shape}")

Registros con código 'MP' antes de eliminar: 224
Registros con código 'MP' después de eliminar: 0
Nuevas dimensiones del DataFrame: (12546, 21)

#Para las columnas que tienen que ver con la ICU, cambia los valores faltantes por 0.

In [20]:
# Columnas con ICU
columnas_icu = ['Number of ICU Beds','Number of Adult ICU Beds','Number of Pediatric ICU Beds','Number of ICU Beds Occupied',
                'Number of Adult ICU Beds Occupied','Number of Pediatric ICU Beds Occupied']
# Cambiamos los vacios por 0
hospitalData[columnas_icu] = hospitalData[columnas_icu].fillna(0)

# Mostramos el DataFrame
#hospitalData.head(2214) ## Para vizualizar el dato 2248 y2252
hospitalData

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of ICU Beds Occupied,Number of Adult ICU Beds Occupied,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications
0,2023-12-08,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,1309.0,845.0,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS
1,2023-12-08,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,1014.0,817.0,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN
2,2023-12-08,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,468.0,446.0,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN
3,2023-12-08,WY,1318.0,1142.0,25.0,559.0,534.0,6.0,114.0,109.0,...,40.0,40.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,AOCNP/JCI/CARN/CBN/CARN/JCI/ACS
4,2023-08-19,AK,1354.0,1192.0,77.0,1054.0,939.0,43.0,184.0,126.0,...,139.0,86.0,8.0,11.0,1.0,NaN,NaN,NaN,NaN,CARN/ISO/AOCNP/CARN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12765,2023-12-08,VA,16500.0,15161.0,911.0,11303.0,10467.0,594.0,2276.0,1856.0,...,1425.0,1188.0,121.0,155.0,6.0,NaN,NaN,NaN,NaN,CPAN/AOCNP/CPEN/DWC/CPEN/DWC/CPEN/CPEN/JCI/CCT...
12766,2023-12-08,VI,168.0,152.0,16.0,89.0,82.0,3.0,17.0,14.0,...,7.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,CPEN/CPEN/AOCNP/CARN/CCTN/ISO/JCI/CPEN/CCTN/ACS
12767,2023-12-08,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,81.0,65.0,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN
12768,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12769,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,9333.0,295183.0,NaN,NaN,3.727144,NaN,NaN

#Conoce el periodo de registro que se encuentra en el archivo para saber cuántos días han transcurrido entre la fecha más reciente y la más antigua.

In [21]:
#Vizualiza la fecha mas antigua
print(f'La fecha más antigua es: {hospitalData["Week Ending Date"].min()}')
#Vizualiza la fecha mas reciente
print(f'La fecha más reciente es: {hospitalData["Week Ending Date"].max()}')
#Resta las fechas
dias_Transcurridos = hospitalData['Week Ending Date'].max() - hospitalData['Week Ending Date'].min()
#Muestra los dias transcurridos
print(f'Los días transcurridos son: {dias_Transcurridos.days}')

La fecha más antigua es: 2020-03-10 00:00:00
La fecha más reciente es: 2024-12-10 00:00:00
Los días transcurridos son: 1736

#Obtén la cantidad total de pacientes pediátricos hospitalizados con COVID-19.

In [22]:
#Suma la cantidad de pacientes
totalPediatricos = hospitalData['Number of Pediatric Patients Hospitalized with COVID-19'].sum()
#Visualiza el total
print(f'La cantidad total de pacientes pediátricos hospitalizados con COVID-19 es: {totalPediatricos}')

La cantidad total de pacientes pediátricos hospitalizados con COVID-19 es: 590363.0

#Obtén el promedio de pacientes adultos hospitalizados por RSV.

In [23]:
#Calcula el promedio
promedioAdultos = hospitalData['Number of Adult Patients Hospitalized with RSV'].mean()
#Visualiza el promedio
print(f'El promedio de pacientes adultos hospitalizados por RSV es: {promedioAdultos:.4f}')

El promedio de pacientes adultos hospitalizados por RSV es: 3.7271

#Agrupa por región geográfica y obtén la sumatoria de pacientes adultos hospitalizados con influenza.

In [24]:
#Se seleccionan las columnas, se agrupa y se suman
AgrupacionGeograficaInflu = hospitalData[['Number of Adult Patients Hospitalized with Influenza','Geographic aggregation']].groupby('Geographic aggregation').sum().astype(int)
#Se visualiza la tabla
AgrupacionGeograficaInflu

                        Number of Adult Patients Hospitalized with Influenza
Geographic aggregation
AK                                                                     19
AL                                                                    168
AR                                                                     99
AS                                                                      0
AZ                                                                    398
CA                                                                    713
CO                                                                     39
CT                                                                     63
DC                                                                     12
DE                                                                     85
FL                                                                    663
GA                                                                    247
GU                                                                      8
HI                                                                     44
IA                                                                     34
ID                                                                     54
IL                                                                    166
IN                                                                    134
KS                                                                     68
KY                                                                    134
LA                                                                    199
MA                                                                     16
MD                                                                     31
ME                                                                     43
MI                                                                     57
MN                                                                    126
MO                                                                     65
MS                                                                     90
MT                                                                     22
NC                                                                    393
ND                                                                      9
NE                                                                     25
NH                                                                     31
NJ                                                                     69
NM                                                                     30
NV                                                                     73
NY                                                                    759
OH                                                                   1412
OK                                                                    303
OR                                                                     36
PA                                                                   1684
PR                                                                    214
RI                                                                    101
SC                                                                     64
SD                                                                      7
TN                                                                    141
TX                                                                    430
USA                                                                  9837
UT                                                                     30
VA                                                                    110
VI                                                                      0
VT                                                                     11
WA                                                                     37
WI                                                                     20
WV                                                                      3
WY                                                                     15

#Crea una columna derivada llamada "Percent of Adult ICU Beds Occupied" con el porcentaje de ocupación para las camas de los adultos en la ICU.

In [25]:
#Agrega la columna y se calcula el porcentaje
hospitalData['Percent of Adult ICU Beds Occupied'] = (hospitalData['Number of Adult ICU Beds Occupied']*100 / hospitalData['Number of Adult ICU Beds']).round(2)
#se visualiza la columna agregada
hospitalData

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Adult ICU Beds Occupied,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adult ICU Beds Occupied
0,2023-12-08,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,845.0,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS,79.79
1,2023-12-08,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,817.0,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN,66.31
2,2023-12-08,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,446.0,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN,74.96
3,2023-12-08,WY,1318.0,1142.0,25.0,559.0,534.0,6.0,114.0,109.0,...,40.0,0.0,4.0,0.0,NaN,NaN,NaN,NaN,AOCNP/JCI/CARN/CBN/CARN/JCI/ACS,36.70
4,2023-08-19,AK,1354.0,1192.0,77.0,1054.0,939.0,43.0,184.0,126.0,...,86.0,8.0,11.0,1.0,NaN,NaN,NaN,NaN,CARN/ISO/AOCNP/CARN,68.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12765,2023-12-08,VA,16500.0,15161.0,911.0,11303.0,10467.0,594.0,2276.0,1856.0,...,1188.0,121.0,155.0,6.0,NaN,NaN,NaN,NaN,CPAN/AOCNP/CPEN/DWC/CPEN/DWC/CPEN/CPEN/JCI/CCT...,64.01
12766,2023-12-08,VI,168.0,152.0,16.0,89.0,82.0,3.0,17.0,14.0,...,7.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,CPEN/CPEN/AOCNP/CARN/CCTN/ISO/JCI/CPEN/CCTN/ACS,50.00
12767,2023-12-08,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,65.0,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN,67.71
12768,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12769,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,9333.0,295183.0,NaN,NaN,3.727144,NaN,NaN,NaN

#Crea un *dataframe* llamado "filtro", con las filas de los hospitales que tengan más de 300 camas "disponibles" para adultos en la ICU; y las columnas de identificación geográfica y las relacionadas, con la cantidad de pacientes con alguna de las enfermedades respiratorias de los adultos.

In [26]:
#Calculamos la cantidad de camas disponibles
disponibles = hospitalData['Number of Adult ICU Beds'] -  hospitalData['Number of Adult ICU Beds Occupied']

#Columnas que visualizaremos
columnas_EnfermedadesAdultos = [
    'Geographic aggregation',
    'Number of Adult Patients Hospitalized with COVID-19',
    'Number of Adult Patients Hospitalized with Influenza',
    'Number of Adult Patients Hospitalized with RSV'
]
#Seleccionamos las filas con mas de 300 camas disponibles y las columnas
filtro = hospitalData.loc[disponibles > 300, columnas_EnfermedadesAdultos]
filtro

,Geographic aggregation,Number of Adult Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV
1,WI,84.0,NaN,NaN
8,AZ,128.0,NaN,NaN
9,CA,1412.0,NaN,NaN
10,CO,80.0,NaN,NaN
14,FL,1563.0,NaN,NaN
...,...,...,...,...
12759,SC,154.0,NaN,NaN
12761,TN,164.0,NaN,NaN
12762,TX,786.0,NaN,NaN
12763,USA,9333.0,NaN,NaN
12765,VA,155.0,NaN,NaN

#Crea un *dataframe* llamado "registros2024" que tenga todos los registros del año 2024.

In [27]:
#Seleccionamos los registros del 2024 y los guardamos en registros2024
registros2024 = hospitalData[hospitalData['Week Ending Date'].dt.year == 2024]
#Mostramos
registros2024

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Adult ICU Beds Occupied,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adult ICU Beds Occupied
1144,2024-06-01,AK,1351.0,1189.0,75.0,1014.0,891.0,47.0,188.0,126.0,...,84.0,7.0,28.0,1.0,0.0,0.0,0.0,1.0,CPEN/DWC/CPEN/DWC/CPEN/CPAN,66.67
1145,2024-06-01,AL,12547.0,11735.0,497.0,10010.0,9365.0,304.0,1597.0,1519.0,...,1323.0,42.0,430.0,28.0,NaN,NaN,NaN,NaN,DWC,87.10
1146,2024-06-01,AR,7642.0,7022.0,422.0,5297.0,4857.0,306.0,1216.0,939.0,...,688.0,55.0,238.0,6.0,6.0,0.0,4.0,0.0,DWC,73.27
1147,2024-06-01,AS,150.0,122.0,28.0,83.0,63.0,14.0,7.0,7.0,...,5.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,CRN/AOCNP/CRN/CCTN/DWC,71.43
1148,2024-06-01,AZ,13449.0,11839.0,877.0,11340.0,10002.0,702.0,2047.0,1539.0,...,1141.0,224.0,441.0,28.0,18.0,0.0,3.0,4.0,DWC/CCTN/CRN/CRN/AOCNP,74.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3761,2024-11-16,VT,1038.0,898.0,126.0,723.0,673.0,50.0,110.0,80.0,...,51.0,21.0,8.0,0.0,0.0,0.0,0.0,1.0,CRN/ACS/CARN/CPEN/CPEN/DWC/JCI,63.75
3762,2024-11-16,WA,10653.0,9449.0,1154.0,9230.0,8307.0,920.0,1502.0,1009.0,...,799.0,392.0,93.0,3.0,14.0,1.0,11.0,9.0,CPEN/ISO/AOCNP/CARN/CCTN/AOCNP/CRN/CPEN/CRN,79.19
3763,2024-11-16,WI,11146.0,9756.0,1334.0,8060.0,7209.0,823.0,1675.0,1179.0,...,840.0,349.0,95.0,6.0,3.0,0.0,1.0,4.0,ISO/CPEN/CBN/CBN/CPEN,71.25
3764,2024-11-16,WV,5723.0,4944.0,779.0,3930.0,3682.0,243.0,794.0,660.0,...,515.0,95.0,63.0,1.0,2.0,0.0,3.0,2.0,CPAN/CCTN/CCTN/CRN/ISO/CPAN,78.03
3765,2024-11-16,WY,919.0,817.0,43.0,359.0,345.0,5.0,80.0,77.0,...,28.0,0.0,11.0,0.0,1.0,0.0,0.0,0.0,JCI/CBN/ISO/JCI/ACS/ISO/CRN/JCI,36.36

#Crear una columna derivada con el conteo de la cantidad de certificaciones que tiene cada hospital; es decir, cuenta la cantidad de elementos que hay en la columna de certificaciones separándolas con /

In [28]:
#Cuenta la cantidad de certificaciones separadas por /
cantidadCertificaciones = hospitalData['Certifications'].str.split('/').str.len()
#Agrega la columna pasando la cantidad de certificaciones
hospitalData['Cantidad de Certificaciones'] = cantidadCertificaciones
#Muestra
hospitalData

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adult ICU Beds Occupied,Cantidad de Certificaciones
0,2023-12-08,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS,79.79,10.0
1,2023-12-08,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN,66.31,4.0
2,2023-12-08,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN,74.96,1.0
3,2023-12-08,WY,1318.0,1142.0,25.0,559.0,534.0,6.0,114.0,109.0,...,0.0,4.0,0.0,NaN,NaN,NaN,NaN,AOCNP/JCI/CARN/CBN/CARN/JCI/ACS,36.70,7.0
4,2023-08-19,AK,1354.0,1192.0,77.0,1054.0,939.0,43.0,184.0,126.0,...,8.0,11.0,1.0,NaN,NaN,NaN,NaN,CARN/ISO/AOCNP/CARN,68.25,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12765,2023-12-08,VA,16500.0,15161.0,911.0,11303.0,10467.0,594.0,2276.0,1856.0,...,121.0,155.0,6.0,NaN,NaN,NaN,NaN,CPAN/AOCNP/CPEN/DWC/CPEN/DWC/CPEN/CPEN/JCI/CCT...,64.01,11.0
12766,2023-12-08,VI,168.0,152.0,16.0,89.0,82.0,3.0,17.0,14.0,...,0.0,1.0,0.0,NaN,NaN,NaN,NaN,CPEN/CPEN/AOCNP/CARN/CCTN/ISO/JCI/CPEN/CCTN/ACS,50.00,10.0
12767,2023-12-08,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN,67.71,10.0
12768,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12769,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,9333.0,295183.0,NaN,NaN,3.727144,NaN,NaN,NaN,NaN

#Busca todos los hospitales que cumplan con la certificación CRN y déjalos en un *dataframe* llamado "CRNData".

In [29]:
#Busca en la columna certificacion CRN y selecciona toda la fila
CRNData = hospitalData[hospitalData['Certifications'].str.contains('CRN',case=False, na=False)]
#Muestra
CRNData

,Week Ending Date,Geographic aggregation,Number of Inpatient Beds,Number of Adult Inpatient Beds,Number of Pediatric Inpatient beds,Number of Inpatient Beds Occupied,Number of Adult Inpatient Beds Occupied,Number of Pediatric Inpatient Beds Occupied,Number of ICU Beds,Number of Adult ICU Beds,...,Number of Pediatric ICU Beds Occupied,Number of Adult Patients Hospitalized with COVID-19,Number of Pediatric Patients Hospitalized with COVID-19,Number of Adult Patients Hospitalized with Influenza,Number of Pedatric Patients Hospitalized with Influenza,Number of Adult Patients Hospitalized with RSV,Number of Pediatric Patients Hospitalized with RSV,Certifications,Percent of Adult ICU Beds Occupied,Cantidad de Certificaciones
0,2023-12-08,WA,10650.0,9282.0,482.0,9040.0,8117.0,339.0,1623.0,1059.0,...,62.0,222.0,4.0,NaN,NaN,NaN,NaN,DWC/CARN/CRN/CBN/CBN/CPEN/DWC/CPEN/CPAN/ACS,79.79,10.0
1,2023-12-08,WI,10752.0,9824.0,425.0,7574.0,7027.0,286.0,1566.0,1232.0,...,71.0,84.0,2.0,NaN,NaN,NaN,NaN,AOCNP/ACS/CARN/CRN,66.31,4.0
2,2023-12-08,WV,4813.0,4556.0,256.0,3701.0,3562.0,139.0,639.0,595.0,...,23.0,47.0,0.0,NaN,NaN,NaN,NaN,CRN,74.96,1.0
6,2023-08-19,AR,7453.0,6803.0,427.0,5201.0,4724.0,295.0,1143.0,865.0,...,76.0,91.0,6.0,NaN,NaN,NaN,NaN,CRN/AOCNP/AOCNP/JCI/AOCNP,73.06,5.0
10,2023-08-19,CO,10249.0,8986.0,687.0,6741.0,5936.0,371.0,1642.0,1275.0,...,61.0,80.0,5.0,NaN,NaN,NaN,NaN,CRN/CPAN/JCI/CPEN/CCTN/CPEN/AOCNP,60.24,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12754,2023-12-08,OK,8386.0,7568.0,409.0,5635.0,5137.0,281.0,1129.0,893.0,...,61.0,67.0,9.0,NaN,NaN,NaN,NaN,ACS/ACS/CARN/CRN/CBN/CBN/CBN,71.22,7.0
12759,2023-12-08,SC,9823.0,9250.0,436.0,7510.0,7106.0,261.0,1591.0,1239.0,...,57.0,154.0,10.0,NaN,NaN,NaN,NaN,CBN/DWC/CPAN/ACS/CCTN/CRN/CRN,66.51,7.0
12760,2023-12-08,SD,2150.0,1974.0,121.0,1402.0,1239.0,61.0,297.0,235.0,...,6.0,10.0,1.0,NaN,NaN,NaN,NaN,ISO/AOCNP/JCI/CBN/CBN/CRN,52.77,6.0
12763,2023-12-08,USA,681406.0,618736.0,37598.0,508063.0,465598.0,24107.0,98373.0,75984.0,...,6116.0,9333.0,442.0,NaN,NaN,NaN,NaN,CRN/ISO,71.00,2.0
12767,2023-12-08,VT,1171.0,1034.0,61.0,810.0,767.0,14.0,129.0,96.0,...,2.0,17.0,0.0,NaN,NaN,NaN,NaN,CPEN/CRN/ACS/CBN/ISO/ACS/JCI/ISO/CPAN/CPEN,67.71,10.0

#Almacena el *dataframe* modificado y los *dataframes* creados en los pasos anteriores en un mismo archivo de Excel llamado "datosHospitalesProcesados.xlsx". Cada *dataframe* deberá estar en una hoja diferente.

In [30]:
#Se crea el archivo
with pd.ExcelWriter('/content/datosHospitalesProcesados.xlsx') as writer:

  #Se crean las hojas en el archivos
  hospitalData.to_excel(writer, sheet_name='General_Modificado', index=False)
  filtro.to_excel(writer, sheet_name='Filtro_Camas_ICU', index=False)
  registros2024.to_excel(writer, sheet_name='Registros_2024', index=False)
  CRNData.to_excel(writer, sheet_name='Certificaciones_CRN', index=False)

#Se imprime el mensaje que se ha creado
print("¡El archivo 'datosHospitalesProcesados.xlsx' ha sido creado y exportado exitosamente con todas sus hojas!")

¡El archivo 'datosHospitalesProcesados.xlsx' ha sido creado y exportado exitosamente con todas sus hojas!